//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpAdminData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientContract
    {
        public int ClientContractID { get; set; }
        public int ClientID { get; set; }
        public string Month { get; set; }
        public string Year { get; set; }
        public Nullable<decimal> AdditionalAmmount { get; set; }
        public Nullable<decimal> Ammount { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
